spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:mem:restaurants
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:restaurants
    username: sa
    password:

  cache:
    cache-names:
      - users
      - restaurants
      - restaurantById
      - menusByRestaurant
      - menuByRestaurantAndDate
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  level:
    root: WARN
    ru.javaops.bootjava: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

springdoc.swagger-ui.path: /
